### ISSUE TITLE
Unpaid leave is shown as negative flex time saldo change in calendar

### ISSUE THREAD

**Issue by nakkje** [solinor/solinor-invoice-checking#34]
Flex saldo change calendar: 
![image](https://user-images.githubusercontent.com/2685330/36305982-92946f80-131e-11e8-96fb-049653002436.png)
Month's row in summary: 
![image](https://user-images.githubusercontent.com/2685330/36305989-9a10058a-131e-11e8-8a41-0133bcdf76e8.png)

**Comment by ojarva** [comment]
Thanks, will fix
